color: true
dry-run: null
hookfiles: hooks
language: go
require: null
server: ./dredd
server-wait: 3
init: false
custom: {}
names: false
only: []
reporter: []
output: []
header: []
sorted: false
user: null
inline-errors: false
details: false
method: []
loglevel: debug
path: []
hooks-worker-timeout: 10000
hooks-worker-connect-timeout: 5000
hooks-worker-connect-retry: 1000
hooks-worker-after-connect-wait: 500
hooks-worker-term-timeout: 10000
hooks-worker-term-retry: 1000
hooks-worker-handler-host: 127.0.0.1
hooks-worker-handler-port: 61321
config: ./dredd.yml
blueprint: api-description.apib
endpoint: "http://127.0.0.1:3000"
